# Generated by Django 2.0.4 on 2018-04-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='regdate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='university',
        ),
    ]
